Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/myApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('ytDownloader.urls'))
]

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/urls.py
from unicodedata import name
from django.urls import path, include
from . import views

app_name = 'YT-downloader'

urlpatterns = [
	path('', views.ytd, name="ytd"),
	path('download/', views.download_page, name="download"),
	path('download/<res>/', views.success, name="success"),
	path('about/', views.about, name="about"),
	path('music/', views.music, name="music"),
	path('download-music/', views.download_music, name="download-music"),
	path('download-playlist/', views.playlist, name="download-playlist"),
	path('contact/', views.contact, name='contact'),
]

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/models.py
from django.db import models

# Create your models here.

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/views.py
from django.shortcuts import render
from django.http import HttpResponse
from pytube import YouTube, Playlist
import os
from wsgiref.util import FileWrapper
import shutil
from django.contrib import messages
from requests import request


# Create your views here.

def ytd(request):
    return render(request, 'ytd.html')


def download_page(request):
    global url
    url = request.GET.get('url')

    yt = YouTube(url)
    global streams
    streams = yt.streams

    res = []
    ores = []
    for i in streams:
        onlyres = i.resolution

        string = str(i.resolution) + ' ' + str(i.filesize_approx // 1048576) + 'mb'

        res.append(string)
        ores.append(onlyres)

    ores = list(dict.fromkeys(ores))

    try:
        for j in range(len(ores)):
            if ores[j] == None:
                ores.pop(j)

    except:
        pass

    for k in range(len(ores)):
        ores[k] = ores[k] + ' ' + str(streams.filter(res=ores[k]).first().filesize // 1048576) + 'mb'

    title = yt.title
    author = yt.author
    length = str(yt.length // 60) + ' minutes'
    if length == 0:
        length = str(yt.length) + ' seconds'

    thumbnail = yt.thumbnail_url
    print(thumbnail)

    res = list(dict.fromkeys(res))

    return render(request, 'download.html', {
        'onlyres': ores,
        'res': res,
        'title': title,
        'author': author,
        'length': length,
        'thumbnail': thumbnail,
    })


def success(request, res):
    global url

    homedir = os.path.expanduser("~")

    dirs = homedir + '/Downloads/'

    yt = YouTube(url)
    title = yt.title
    print(title)
    res, b = res.split()
    size = streams.filter(res=res).first().filesize // 1048576
    print(size)
    if request.method == 'POST' and size < 900:

        streams.filter(res=res).first().download(output_path=dirs, filename="video.mp4")
        file = FileWrapper(open(f'{dirs}/video.mp4', 'rb'))
        # path =  '/home/runner/youtube-video-downloader/downloads/video' + '.mp4'
        # o = dirs + title + '.mp4'
        response = HttpResponse(file, content_type='application/vnd.mp4')
        response['Content-Disposition'] = 'attachment; filename = "video.mp4"'
        os.remove(f'{dirs}/video.mp4')
        return response
    # return render(request, 'success.html')

    else:
        return render(request, 'error.html')


def about(request):
    return render(request, 'about.html')


def music(request):
    return render(request, 'music.html')


def download_music(request):
    url = request.GET.get('url')
    yt = YouTube(url)
    title = yt.title

    stream = yt.streams.filter(only_audio=True).first()
    # size = stream.filesize

    homedir = os.path.expanduser("~")

    dirs = homedir + '/Downloads/'
    size = stream.filesize // 1048576

    # messages.success(request, 'The download has been started, do not close this page')
    if request.method == 'POST' and size < 900:
        stream.download(output_path=dirs, filename=f"{title}.mp3")
        file = FileWrapper(open(f'{dirs}/{title}.mp3', 'rb'))
        # path =  '/home/runner/youtube-video-downloader/downloads/video' + '.mp4'
        # o = dirs + title + '.mp4'
        response = HttpResponse(file, content_type='audio.mp3')
        response['Content-Disposition'] = f'attachment; filename = "{title}.mp3"'
        os.remove(f'{dirs}/{title}.mp3')
        return response
    # return render(request, 'success.html')
    else:
        return render(request, 'error.html')


def playlist(request):
    url = request.GET.get('url')

    playlist = Playlist(url)
    title = playlist.title
    videos = playlist.videos

    homedir = os.path.expanduser("~")

    dirs = homedir + f'/Downloads'

    size = 0

    for i in videos:
        stream = i.streams.filter(only_audio=True).first()
        size += stream.filesize // 1048576

    # messages.success(request, 'The download has been started, do not close this page')
    if size < 900:
        for i in videos:
            name = i.title
            stream = i.streams.filter(only_audio=True).first()
            stream.download(output_path=f'{dirs}/{title}', filename=f"{name}.mp3")

        path = shutil.make_archive(title, 'zip', f'{dirs}/{title}')

        file = FileWrapper(open(path, 'rb'))

        response = HttpResponse(file, content_type='application/force-download')
        response['Content-Disposition'] = f'attachment; filename = "{title}.zip"'
        os.remove(path)
        os.remove(f'{dirs}/{title}')
        return response

    else:
        return render(request, 'error.html')


def contact(request):
    return render(request, 'contact.html')

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/templates/about.html
{% extends 'layout.html' %}

{% block content %}
<div class="heading">
	About this site	
</div>

<div class="ct">
	This site downloads yt videos
</div>
{% endblock %}

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/templates/contact.html
{% extends 'layout.html' %}

{% block content %}
<h2 style="padding-top: 50px;" class="ct">
	Contact Me
</h2>
<div class="contact">
<form class="forms" action="https://formsubmit.co/dev.marvel.avengers@gmail.com" method="post" autocomplete="off">
		
	<label for="name" >Your Name</label>
	<input type="text" name="name" class="input" placeholder="Your Name" required>

	<label for="email">Email</label>
	<input type="email" class="input" name="email" placeholder="Email" required>

	<label for="message">Message</label>
	<textarea name="message" placeholder="Message"></textarea required>

	<input class="input" type="submit" value="Submit">

</form>
</div>
{% endblock %}

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/templates/download.html
{% extends 'layout.html' %}

{% block content %}
		<div class="heading">
			Download Page
		</div>

		<div class="thumbnail">
			<img class="thumbnail-image" src="{{thumbnail}}" alt="Error loading thumnnail">
		</div>

		<div class="ct">
			Title: {{title}}
			<br>
			<br>
			By: {{author}}
			<br>
			<br>
			Length: {{length}}
		</div>

		<div class="ct">
			Choose your prefered attributes from below
		</div>

		<div class="ct">
			Only 144, 360 and 720p include audio
		</div>
		
		<table>
			<thead>
				<tr class="table-heading">
					<th scope="col">Attributes</th>
					<th scope="col">Download</th>
				</tr>
			</thead>

			{% for i in onlyres %}

			<tbody>
				<tr>
					<td data-label="Attributes">{{i}}</td>
					<td data-label="Download">
						<form action="{% url 'YT-downloader:success' i %}" method="post">
							{% csrf_token %}
							<button type="submit" value="Download" class="download-btn">Download</button>
						</form>
					</td>
				</tr>

				{% endfor %}

			</tbody>
		</table>
{% endblock %}

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/templates/error.html
404 not found

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>YT Video Download</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'styles.css' %}?{% now "U" %}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	</head>
	<body class="home-page">
		<header>
			<p class="logo">Youtube Video Downloader</p>
			<input type="checkbox" id="click">
			<label for="click" class="menu-btn">
				<i class="fas fa-bars"></i>
			</label>
		
			<ul class="nav__links">
				<li><a href="/">Youtube</a></li>
				<li><a href="/music/">Music</a></li>
				<li><a href="/about/">About</a></li>
			</ul>
		
			<a class="cta" href="/contact/"><button>Contact</button></a>
		</header>

		{% block content %}
		{% endblock %}

		</body>

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/templates/music.html
{% extends 'layout.html' %}

{% block content %}
		<div class="heading">
			Single Music
		</div>
		
		<form action="/download-music/" class="search-form" method="get">
			<div class="form">
				<!--<label for="link">Enter Link</label>-->
				<input type="text" id="link" name="url" placeholder="Enter link here">
			</div>
			<button type="submit">Enter</button>
		</form>

		<div class="heading">
			Playlist
		</div>
		
		<form action="/download-playlist/" class="search-form" method="get">
			<div class="form">
				<!--<label for="link">Enter Link</label>-->
				<input type="text" id="link" name="url" placeholder="Enter link here">
			</div>
			<button id="idk" type="submit">Enter</button>
		</form>
		<script>
			document.getElementById('idk').addEventListener("click", function(){ alert("Download has started pls wait 5-10 mins"); });
		</script>
{% endblock %}

Youtube-Video-Downloader-Django-main/Youtube-Video-Downloader-Django-main/myApp/ytDownloader/templates/ytd.html
{% extends 'layout.html' %}

{% block content %}
		<div class="heading">
			Enter Yt Video link here	
		</div>
		
		<form action="download/" class="search-form" method="get">
			<div class="form">
				<!--<label for="link">Enter Link</label>-->
				<input type="text" id="link" name="url" placeholder="Enter link here">
			</div>
			<button type="submit">Enter</button>
		</form>
{% endblock %}